### PR TITLE
Check if Google Authenticator entries are encrypted

### LINKED ISSUE #918: Import from Google Authenticator fails
###### Info

* __Version__: 2.0.3
* __Source__: F-Droid
* __Vault encrypted__: Yes, No biometrics
* __Device__: OnePlus 6
* __Android version and ROM__: 11; OxygenOS 11.1.2.2

###### Steps to reproduce

1. Have a rooted device
2. Import from Google Authenticator either via the Import from App feature or by importing the database file

###### What do you expect to happen?

Successful import of the codes from Google Authenticator into Aegis

###### What happens instead?

Prompted with "One or more errors occurred during the import"

###### Other

I believe Google Authenticator got updated recently, maybe the database structure changed.

screenshot

###### Log

```
com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 81

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 59

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 59

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 0

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 81

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 81

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 59

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 59

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 8

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 9

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 0

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 81

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 81

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 81

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 59

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 81

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 81

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 59

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 9

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 0

com.beemdevelopment.aegis.encoding.EncodingException: java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 81
```

### PR DESCRIPTION
**Pull request by CristianAUnisa**
Fix #918 

I'm unsure about this tho. I tested it with two Google Authenticator versions, but is it possible that unencrypted entries exist in the new version?

### CODE REVIEW

File: app/src/main/java/com/beemdevelopment/aegis/importers/GoogleAuthImporter.java [hunk 1]
```diff
@@ -114,12 +123,22 @@ public Entry(Cursor cursor) {
             _email = SqlImporterHelper.getString(cursor, "email", "");
             _issuer = SqlImporterHelper.getString(cursor, "issuer", "");
             _counter = SqlImporterHelper.getLong(cursor, "counter");
+            if(cursor.getColumnIndex("isencrypted") != -1 && SqlImporterHelper.getInt(cursor, "isencrypted") > 0) {
+                _isencrypted = true;
+            } else {
+                _isencrypted = false;
+            }
```
Comment (alexbakker) [inline app/src/main/java/com/beemdevelopment/aegis/importers/GoogleAuthImporter.java:130]: An inline expression is a bit shorter. Also ``_isEncrypted`` instead of ``_isencrypted``.

```java
_isEncrypted = cursor.getColumnIndex("isencrypted") != -1 && SqlImporterHelper.getInt(cursor, "isencrypted") > 0
```

File: app/src/main/res/values-it-rIT/strings.xml [hunk 2]
```diff
@@ -338,6 +338,7 @@
     <string name="importer_help_steam">Seleziona una copia di <b>/data/data/com.valvesoftware.android.steam.community/files/Steamguard-*.json</b>, situata nella directory della memoria interna di Steam.</string>
     <string name="importer_help_totp_authenticator">Seleziona un file di esportazione di TOTP Authenticator.</string>
     <string name="importer_help_winauth">Seleziona un file di esportazione di WinAuth.</string>
+    <string name="importer_encrypted_exception_google_authenticator">Voce criptata:</string>
```
Comment (alexbakker) [inline app/src/main/res/values-it-rIT/strings.xml:341]: This will get overwritten when we import changes from Crowdin. Could you remove it?

File: app/src/main/res/values/strings.xml [hunk 3]
```diff
@@ -388,6 +388,8 @@
     <string name="importer_help_totp_authenticator">Supply a TOTP Authenticator export file.</string>
     <string name="importer_help_winauth">Supply a WinAuth export file.</string>
 
+    <string name="importer_encrypted_exception_google_authenticator">Encrypted entry:</string>
```
Comment (alexbakker) [inline app/src/main/res/values/strings.xml:391]: Could you change this to "Encrypted entry was skipped: %s" and pass the "email" as a parameter?

**Review by alexbakker — CHANGES_REQUESTED** [review]
Thanks for working on this! Just a couple of small changes and we'll merge this.

I think you're right, it's likely that we'll only see either all plain text secrets, or all encrypted secrets. But it's hard to be sure, so I don't think it hurts to support a mix of plain text and encrypted secrets just in case for now.

**Comment by CristianAUnisa** [comment]
Just committed the new changes and squashed them!

**Review by alexbakker — APPROVED** [review]
Thanks!
